extends:
    - "plugin:react-hooks/recommended"
ignorePatterns:
    - dist
    - dist-electron
plugins:
    - react-refresh
rules:
    react-refresh/only-export-components:
        - warn
        - allowConstantExport: true
