export const DELETE_SUBSCRIBER_TIMEOUT_MS = 1 * 60 * 1000; // 1 minute
export const NOTIFY_SUBSCRIBER_TIMEOUT_MS = DELETE_SUBSCRIBER_TIMEOUT_MS / 2; // 30 seconds
export const MAX_FRAME_ID_CACHE_SIZE = 8;
